feat: Adds support for the rho markets finance protocol to ethena.
ethena-labs/ethena_sats_adapters pull request #10
Opened 2024-07-07 02:31 UTC by CarlWiles

2024-07-17 04:00 UTC, deHB6 requested changes

2024-07-17 04:00 UTC, deHB6 commented on utils/rho_markets.py
> +        return balance * exchangeRate / (1e18 * 1e18)
should be 10e18 * 10e18 I think?

2024-07-17 04:00 UTC, deHB6 commented on constants/rho_markets.py
> +RHO_MARKETS_SCROLL_RUSDE_ADDRESS = w3_scroll.to_checksum_address("0x5fF1926507f6e71bFbd5f9897fBaeF021E2F77CA".lower())
dont need .lower()

2024-07-17 07:20 UTC, CarlWiles commented on utils/rho_markets.py
> +        return balance * exchangeRate / (1e18 * 1e18)
10e18 means 10 \times 10^{18}, which is incorrect and will result in your calculations being off by a factor of 10^{20}.

2024-07-22 13:03 UTC, FJ-Riveros requested changes
Could you also solve the merge conflicts please?

2024-07-22 13:03 UTC, FJ-Riveros commented on utils/rho_markets.py
> +                                response.status_code}: {response.text}")
Getting an error here, it should be: 
```suggestion
  raise Exception( 
    f"Query failed with status code { response.status_code}: {response.text}"
   )
```

2024-07-22 13:03 UTC, FJ-Riveros commented on utils/rho_markets.py
> +    def fetch_compound_users(asset_symbol):
Missing the self here, giving an error. It should be: 
```suggestion
    def fetch_compound_users(self, asset_symbol):
```

2024-07-22 13:03 UTC, FJ-Riveros commented on utils/rho_markets.py
> +                accounts = data['data']['accounts']
Here I'm getting the following error from your API: 
`{'errors': [{'message': 'indexing_error'}]}`

2024-07-25 02:28 UTC, CarlWiles commented on utils/rho_markets.py
> +    def fetch_compound_users(asset_symbol):
Let's close this PR, I request a new PR here:
https://github.com/ethena-labs/ethena_sats_adapters/pull/19

2024-07-26 11:59 UTC, closed without merging