add Nuri Exchange Scroll
ethena-labs/ethena_sats_adapters pull request #11
Opened 2024-07-08 16:44 UTC by 0xShad0w

2024-07-17 15:22 UTC, FJ-Riveros requested changes
Could you please take a look at the comments and also fix the merge conflicts please?

2024-07-17 15:22 UTC, FJ-Riveros commented on integrations/nuri.py
> +            start_block = to_block + 1
I believe here its
```suggestion
            start_block += page_size
```

2024-07-17 15:22 UTC, FJ-Riveros commented on integrations/nuri.py
> +                    all_users.add(transfer["args"]["to"])
Here I think that we are returning all the users from Nuri right? 
Is there a way to filter and only return the users from the USDe pools on Nuri?

2024-07-18 22:01 UTC, 0xShad0w commented on integrations/nuri.py
> +                    all_users.add(transfer["args"]["to"])
Thanks for the suggestion. I'm querying the pool directly now instead of the nfpManager contract. Should save some requests

2024-07-19 11:41 UTC, FJ-Riveros approved these changes
LGTM

2024-07-19 11:41 UTC, merged